### ISSUE TITLE
CI can't find tmpdir

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk-docker#30]
## Describe the Bug
When running under the CI system,  the pdk validate command fails because it cannot find a temp directory

## Expected Behavior
pdk validate and other commands would run and complete without error

The image would have everything needed to run this in a CI
## Steps to Reproduce
1. Have pdk module
2. Use gitlab ci
3. use the following or similar ci file that utilizes the docker image

```
---
stages:
  - syntax
  - unit
  - deploy

variables:
  # None of these seem to work
  TMPDIR: '/tmp'
  TMP: '/tmp'
  TEMP: '/tmp'
image: 
  name: puppet/pdk
  entrypoint: [""]


default:
  cache:
    paths:
      - vendor/bundle

validate_6:
  stage: syntax
  script:
    - pdk validate
  variables:
    PDK_PUPPET_VERSION: '6'

test_6:
  stage: unit
  script:
    - pdk test unit
  variables:
    PDK_PUPPET_VERSION: '6'

validate_7:
  stage: syntax
  script:
    - pdk validate
  variables:
    PDK_PUPPET_VERSION: '7'

test_7:
  stage: unit
  script:
    - pdk test unit
  variables:
    PDK_PUPPET_VERSION: '7'
```

## Environment
PDK 2.x

## Additional Context
```
$ pdk validate
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.21.1
pdk (INFO): Running all available validators...
/opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tmpdir.rb:35:in `tmpdir': could not find a temporary directory (ArgumentError)
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tmpdir.rb:112:in `tmpdir'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tmpdir.rb:134:in `create'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tempfile.rb:131:in `initialize'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/cli/exec/command.rb:32:in `new'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/cli/exec/command.rb:32:in `initialize'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/util/bundler.rb:252:in `new'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/util/bundler.rb:252:in `bundle_command'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/util/bundler.rb:100:in `installed?'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/util/bundler.rb:37:in `ensure_bundle!'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/cli/validate.rb:105:in `block (2 levels) in <module:CLI>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/cli.rb:71:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/exe/pdk:6:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/bin/pdk:23:in `load'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/bin/pdk:23:in `<main>'
Cleaning up file based variables
```
